Repository bench-ai/benchkit, pull requests merged in 2023-09, with the labels that each got.

#43 Checkpoints
  .gitignore
  BenchKit/Data/Datasets.py
  BenchKit/Data/Helpers.py
  BenchKit/Miscellaneous/BenchKit.py
  BenchKit/Miscellaneous/MakeTar.py
  BenchKit/Miscellaneous/User.py
  BenchKit/Miscellaneous/Verbose.py
  BenchKit/Miscellaneous/cli/__init__.py
  BenchKit/Miscellaneous/cli/server.py
  BenchKit/Miscellaneous/manage.txt
  BenchKit/Miscellaneous/requests/__init__.py
  BenchKit/Miscellaneous/requests/dataset.py
  BenchKit/Miscellaneous/requests/graph.py
  BenchKit/Miscellaneous/requests/model_save.py
  BenchKit/Miscellaneous/requests/server.py
  BenchKit/Miscellaneous/requests/user.py
  BenchKit/Miscellaneous/requests/version.py
  BenchKit/Miscellaneous/utils/__init__.py
  BenchKit/Miscellaneous/utils/bucket.py
  BenchKit/Miscellaneous/utils/tar.py
  BenchKit/Tracking/Tracker.py
  BenchKit/Train/Helpers.py
  BenchKit/Train/TrainScript.txt
  BenchKit/distributed/__init__.py
  BenchKit/distributed/accelerate/__init__.py
  BenchKit/distributed/accelerate/helpers.py
  BenchKit/distributed/accelerate/tracking/__init__.py
  BenchKit/distributed/accelerate/tracking/bench_tracker.py
  BenchKit/tracking/__init__.py
  BenchKit/tracking/config.py
  BenchKit/tracking/graphs/__init__.py
  BenchKit/tracking/graphs/base_graph.py
  BenchKit/tracking/graphs/time_series.py
  BenchKit/tracking/helpers.py
  BenchKit/tracking/visualizer.py
  setup.cfg
Labels: enhancement

#48 added dynamic versioning
  CONTRIBUTING.md
  README.md
  src/benchkit/misc/verbose.py
Labels: bug

#49 push to version one
  pyproject.toml
Labels: enhancement

#52 Wdos path fix
  pyproject.toml
  src/benchkit/data/datasets.py
  src/benchkit/data/helpers.py
  src/benchkit/misc/requests/dataset.py
  src/benchkit/misc/requests/graph.py
  src/benchkit/misc/requests/model_save.py
  src/benchkit/misc/requests/server.py
  src/benchkit/misc/requests/user.py
  src/benchkit/misc/requests/version.py
  src/benchkit/nn/helpers.py
  src/benchkit/tracking/helpers.py
Labels: bug

#54 fixed utf8 issue
  src/benchkit/data/file_saver.py
Labels: bug

#55 bumped version
  pyproject.toml
Labels: build
